---
title: "ggplot2"
author: "AimingLiu"
date: "9/26/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggridges)
```
```{r  load_data,cache=TRUE}
  weather_df = 
  rnoaa::meteo_pull_monitors(c("USW00094728", "USC00519397", "USS0023B17S"),#download weather from these three sets#
                      var = c("PRCP", "TMIN", "TMAX"), 
                      date_min = "2017-01-01",
                      date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY", 
                      USC00519397 = "Waikiki_HA",
                      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```
##making a new plot

add labels
```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = .5)+
  labs(
    title = "Temperature plot",
    x = "Mininal Temp(C) ",
    y = "Maximum Temo(C)",
    caption = "Data from noaa via rnoaa package"
  )+
  scale_x_continuous(
     breaks = c(-15,-5,-20),#heplful if you have something to highlight
     labels = c("-15ยบ C", "0", "15"))
    

```
#colors next
```{r}
ggp_temp_plot = 
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = .5)+
  labs(
    title = "Temperature plot",
    x = "Mininal Temp(C) ",
    y = "Maximum Temo(C)",
    caption = "Data from noaa via rnoaa package"
  )+
   scale_color_hue(name = "Location")
```

```{r}
 ggp_temp_plot + 
  theme(legend.position = "bottom")#change the position of the legend
```
#more than one dataset
```{r}
central_park = 
  weather_df%>%
  filter(name == "CentralPark_NY")

waikiki = 
  weather_df %>% 
  filter(name == "Waikiki_HA")

ggplot(data = waikiki, aes(x = date, y = tmax, color = name)) + 
  geom_point() + 
  geom_line(data = central_park)
```



##create a ggplot#
```{r}
ggplot(weather_df,aes(x = tmin,y = tmax))+geom_point()#add point#
```
```{r}
weather_df%>%
   ggplot(aes(x = tmin,y = tmax))+geom_point()
```

saving initial plots*(mostly don't use this)
```{r}
scatterplot = weather_df%>%
             ggplot(aes(x = tmin,y = tmax))+geom_point()

scatterplot
```
adding color
```{r}
weather_df%>%
   ggplot(aes(x = tmin,y = tmax))+
   geom_point(aes(color = name),alpha = .4)
```
```{r}
  ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = .5) +
  geom_smooth(se = FALSE)+
  facet_grid(. ~ name)#separate change to 3 plots#
```
this is fine but not interesting
```{r}
weather_df%>%
   ggplot(aes(x = date,y = tmax,color = name))+
   geom_point(aes(size = prcp),alpha = .35)+
   geom_smooth(size = 2,se = FALSE)
```
##Some extra stuff
```{r}
  ggplot(weather_df, aes(x = date, y = tmax, color = name)) + 
  geom_smooth(se = FALSE) 
```
2d density

```{r}
#install package ("hexbin")
 weather_df%>%
  ggplot(aes(x = tmax, y = tmin)) + 
  geom_bin2d()
```
##More kinds of plots!
```{r}
 weather_df%>%
  ggplot(aes(x = tmax,color = name))+#color is just outside the bar when you change color to fill it will change the color of bar#
  geom_histogram()
```
```{r}
weather_df%>%
  ggplot(aes(x = tmax,fill = name))+
  geom_histogram(position = "dodge")
```
```{r}
weather_df%>%
  ggplot(aes(x = tmax,fill = name))+
  geom_density(alpha = .3)
```
```{r}
weather_df%>%
  ggplot(aes(x = name,y = tmax))+
  geom_boxplot()
```
```{r}
weather_df%>%
  ggplot(aes(x = name,y = tmax))+
  geom_violin()
```

ridge plots
```{r}
 weather_df%>%
    ggplot(aes(x = tmax,y = name))+
    geom_density_ridges(scale = .85)
```
#saving a plot
```{r}
weather_plot = ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = .5) 

ggsave("weather_plot.pdf", weather_plot, width = 8, height = 5)
```


```{r}

```




  


